import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const url=Deno.env.get("SUPABASE_URL")!, pub=JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")||"{}").default||Deno.env.get("SUPABASE_ANON_KEY")!, sec=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default||Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const authClient=createClient(url,pub,{auth:{persistSession:false,autoRefreshToken:false}}), admin=createClient(url,sec,{auth:{persistSession:false,autoRefreshToken:false}});
async function caller(req:Request){const h=req.headers.get("Authorization")||"";if(!h.startsWith("Bearer "))return null;const {data}=await authClient.auth.getUser(h.slice(7));return data.user||null}
async function isAdmin(u:any){if(!u)return null;const {data}=await admin.from("cmnt_admin_users").select("*").eq("user_id",u.id).maybeSingle();return data?.active?data:null}
const clean=(v:any)=>String(v||"").trim().toLowerCase().replace(/[^a-z0-9_.-]/g,"").slice(0,40),okPass=(v:any)=>typeof v==="string"&&v.length>=8;
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Método não permitido"},405);let b:any={};try{b=await req.json()}catch{return json({error:"JSON inválido"},400)}
if(b.action==="bootstrap"){const {count,error}=await admin.from("cmnt_admin_users").select("id",{count:"exact",head:true});if(error)return json({error:error.message},500);if((count||0)>0)return json({error:"O primeiro administrador já existe."},409);if(clean(b.username||"admin")!=="admin"||String(b.password||"")!=="admin")return json({error:"O primeiro acesso deve usar admin/admin."},400);const c=await admin.auth.admin.createUser({email:"admin@cmnt.local",password:"admin",email_confirm:true,user_metadata:{username:"admin",display_name:"Administrador CMNT"}});if(c.error)return json({error:c.error.message},400);const u=c.data.user!;const m=await admin.auth.admin.updateUserById(u.id,{app_metadata:{role:"cmnt_admin",provider:"email",providers:["email"]}});if(m.error)return json({error:m.error.message},500);const i=await admin.from("cmnt_admin_users").insert({user_id:u.id,username:"admin",email:"admin@cmnt.local",display_name:"Administrador CMNT",role:"cmnt_admin",must_change_password:true});if(i.error){await admin.auth.admin.deleteUser(u.id);return json({error:i.error.message},500)}await admin.from("social_profiles").upsert({id:u.id,username:"admin",display_name:"Administrador CMNT",verified:true});return json({ok:true,email:"admin@cmnt.local"})}
const user=await caller(req),me=await isAdmin(user);if(!user||!me)return json({error:"Acesso administrativo não autorizado."},403);
if(b.action==="me")return json({admin:me});
if(b.action==="list"){const {data,error}=await admin.from("cmnt_admin_users").select("id,user_id,username,email,display_name,role,permissions,active,must_change_password,last_password_change_at,created_at").order("created_at");return error?json({error:error.message},500):json({admins:data||[]})}
if(b.action==="create"){const username=clean(b.username),email=String(b.email||"").trim().toLowerCase(),password=String(b.password||"");if(!username||!email||!okPass(password))return json({error:"Informe usuário, e-mail e senha com pelo menos 8 caracteres."},400);const c=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{username,display_name:String(b.display_name||username)}});if(c.error)return json({error:c.error.message},400);const u=c.data.user!;const m=await admin.auth.admin.updateUserById(u.id,{app_metadata:{role:"cmnt_admin",provider:"email",providers:["email"]}});if(m.error)return json({error:m.error.message},500);const i=await admin.from("cmnt_admin_users").insert({user_id:u.id,username,email,display_name:String(b.display_name||username),role:"cmnt_admin",must_change_password:true,created_by:user.id});if(i.error){await admin.auth.admin.deleteUser(u.id);return json({error:i.error.message},400)}await admin.from("social_profiles").upsert({id:u.id,username,display_name:String(b.display_name||username),verified:true});await admin.from("cmnt_admin_audit_log").insert({actor_user_id:user.id,action:"admin_created",target_user_id:u.id,metadata:{username,email}});return json({ok:true})}
if(b.action==="toggle"){const target=String(b.user_id||"");if(target===user.id)return json({error:"Você não pode desativar a própria conta."},400);const active=!!b.active,r=await admin.from("cmnt_admin_users").update({active,updated_at:new Date().toISOString()}).eq("user_id",target);if(r.error)return json({error:r.error.message},400);await admin.from("cmnt_admin_audit_log").insert({actor_user_id:user.id,action:active?"admin_enabled":"admin_disabled",target_user_id:target});return json({ok:true})}
if(b.action==="reset_password"){const target=String(b.user_id||""),password=String(b.password||"");if(!okPass(password))return json({error:"A nova senha deve ter pelo menos 8 caracteres."},400);const r=await admin.auth.admin.updateUserById(target,{password});if(r.error)return json({error:r.error.message},400);await admin.from("cmnt_admin_users").update({must_change_password:true,last_password_change_at:null,updated_at:new Date().toISOString()}).eq("user_id",target);await admin.from("cmnt_admin_audit_log").insert({actor_user_id:user.id,action:"admin_password_reset",target_user_id:target});return json({ok:true})}
if(b.action==="mark_password_changed"){const r=await admin.from("cmnt_admin_users").update({must_change_password:false,last_password_change_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("user_id",user.id);if(r.error)return json({error:r.error.message},400);await admin.from("cmnt_admin_audit_log").insert({actor_user_id:user.id,action:"password_changed",target_user_id:user.id});return json({ok:true})}
if(b.action==="audit"){const {data,error}=await admin.from("cmnt_admin_audit_log").select("*").order("created_at",{ascending:false}).limit(200);return error?json({error:error.message},500):json({logs:data||[]})}return json({error:"Ação desconhecida."},400)});