create table if not exists public.ava_profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, role text not null default 'student' check (role in ('student','professor','admin','editor')), avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.ava_courses (id uuid primary key default gen_random_uuid(), title text not null, slug text not null unique, description text, workload_hours numeric(6,2), cover_url text, status text not null default 'draft' check (status in ('draft','review','published','archived')), created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.ava_modules (id uuid primary key default gen_random_uuid(), course_id uuid not null references public.ava_courses(id) on delete cascade, title text not null, description text, sort_order integer not null default 0, created_at timestamptz not null default now(), unique(course_id, sort_order));
create table if not exists public.ava_lessons (id uuid primary key default gen_random_uuid(), module_id uuid not null references public.ava_modules(id) on delete cascade, title text not null, slug text not null, lesson_type text not null default 'content' check (lesson_type in ('content','activity','assessment','live')), content text, duration_minutes integer, status text not null default 'draft' check (status in ('draft','review','published','archived')), sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(module_id, sort_order), unique(module_id, slug));
create table if not exists public.ava_materials (id uuid primary key default gen_random_uuid(), lesson_id uuid references public.ava_lessons(id) on delete cascade, course_id uuid references public.ava_courses(id) on delete cascade, title text not null, material_type text not null check (material_type in ('pdf','document','slide','audio','video','link','download')), storage_path text, external_url text, is_public boolean not null default false, created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), check (lesson_id is not null or course_id is not null), check (storage_path is not null or external_url is not null));
create table if not exists public.ava_enrollments (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, course_id uuid not null references public.ava_courses(id) on delete cascade, status text not null default 'active' check (status in ('pending','active','completed','cancelled')), enrolled_at timestamptz not null default now(), completed_at timestamptz, unique(user_id, course_id));
create table if not exists public.ava_progress (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, lesson_id uuid not null references public.ava_lessons(id) on delete cascade, status text not null default 'not_started' check (status in ('not_started','in_progress','completed')), progress_percent numeric(5,2) not null default 0 check (progress_percent between 0 and 100), last_position_seconds integer not null default 0, started_at timestamptz, completed_at timestamptz, updated_at timestamptz not null default now(), unique(user_id, lesson_id));
create table if not exists public.ava_assessments (id uuid primary key default gen_random_uuid(), lesson_id uuid not null references public.ava_lessons(id) on delete cascade, title text not null, instructions text, passing_score numeric(5,2), attempts_allowed integer, created_at timestamptz not null default now());
create table if not exists public.ava_questions (id uuid primary key default gen_random_uuid(), assessment_id uuid not null references public.ava_assessments(id) on delete cascade, prompt text not null, question_type text not null default 'single_choice' check (question_type in ('single_choice','multiple_choice','true_false','text')), options jsonb, correct_answer jsonb, points numeric(8,2) not null default 1, sort_order integer not null default 0);
create table if not exists public.ava_attempts (id uuid primary key default gen_random_uuid(), assessment_id uuid not null references public.ava_assessments(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, score numeric(6,2), passed boolean, answers jsonb, started_at timestamptz not null default now(), submitted_at timestamptz);
create table if not exists public.ava_live_classes (id uuid primary key default gen_random_uuid(), course_id uuid references public.ava_courses(id) on delete cascade, lesson_id uuid references public.ava_lessons(id) on delete set null, instructor_id uuid references auth.users(id) on delete set null, title text not null, provider text not null default 'external', room_url text, recording_url text, scheduled_at timestamptz not null, duration_minutes integer, status text not null default 'scheduled' check (status in ('scheduled','live','finished','cancelled')), access_policy text not null default 'enrolled' check (access_policy in ('public','enrolled','private')), created_at timestamptz not null default now());
create table if not exists public.ava_attendance (id uuid primary key default gen_random_uuid(), live_class_id uuid not null references public.ava_live_classes(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, joined_at timestamptz not null default now(), left_at timestamptz, minutes_attended integer, unique(live_class_id, user_id));
create table if not exists public.ava_recordings (id uuid primary key default gen_random_uuid(), live_class_id uuid not null references public.ava_live_classes(id) on delete cascade, title text not null, storage_path text, external_url text, published boolean not null default false, created_at timestamptz not null default now(), check (storage_path is not null or external_url is not null));
create table if not exists public.ava_certificates (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, course_id uuid not null references public.ava_courses(id) on delete cascade, certificate_code text not null unique, issued_at timestamptz not null default now(), pdf_path text, status text not null default 'valid' check (status in ('valid','revoked')), unique(user_id, course_id));
create table if not exists public.ava_notifications (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, title text not null, message text not null, type text not null default 'info', read_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.ava_audit_log (id bigint generated always as identity primary key, actor_id uuid references auth.users(id) on delete set null, action text not null, entity_type text, entity_id uuid, metadata jsonb, created_at timestamptz not null default now());

create index if not exists ava_modules_course_idx on public.ava_modules(course_id, sort_order);
create index if not exists ava_lessons_module_idx on public.ava_lessons(module_id, sort_order);
create index if not exists ava_enrollments_user_idx on public.ava_enrollments(user_id);
create index if not exists ava_progress_user_idx on public.ava_progress(user_id);
create index if not exists ava_live_classes_schedule_idx on public.ava_live_classes(scheduled_at);

alter table public.ava_profiles enable row level security;
alter table public.ava_courses enable row level security;
alter table public.ava_modules enable row level security;
alter table public.ava_lessons enable row level security;
alter table public.ava_materials enable row level security;
alter table public.ava_enrollments enable row level security;
alter table public.ava_progress enable row level security;
alter table public.ava_assessments enable row level security;
alter table public.ava_questions enable row level security;
alter table public.ava_attempts enable row level security;
alter table public.ava_live_classes enable row level security;
alter table public.ava_attendance enable row level security;
alter table public.ava_recordings enable row level security;
alter table public.ava_certificates enable row level security;
alter table public.ava_notifications enable row level security;
alter table public.ava_audit_log enable row level security;

create policy "ava published courses are readable" on public.ava_courses for select to anon, authenticated using (status = 'published');
create policy "ava published modules are readable" on public.ava_modules for select to anon, authenticated using (exists (select 1 from public.ava_courses c where c.id = course_id and c.status = 'published'));
create policy "ava published lessons are readable" on public.ava_lessons for select to anon, authenticated using (exists (select 1 from public.ava_modules m join public.ava_courses c on c.id = m.course_id where m.id = module_id and c.status = 'published' and ava_lessons.status = 'published'));
create policy "ava own profile readable" on public.ava_profiles for select to authenticated using (id = (select auth.uid()));
create policy "ava own profile insert" on public.ava_profiles for insert to authenticated with check (id = (select auth.uid()));
create policy "ava own profile update" on public.ava_profiles for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));
create policy "ava own enrollments readable" on public.ava_enrollments for select to authenticated using (user_id = (select auth.uid()));
create policy "ava own progress readable" on public.ava_progress for select to authenticated using (user_id = (select auth.uid()));
create policy "ava own progress insert" on public.ava_progress for insert to authenticated with check (user_id = (select auth.uid()));
create policy "ava own progress update" on public.ava_progress for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "ava own attempts readable" on public.ava_attempts for select to authenticated using (user_id = (select auth.uid()));
create policy "ava own attempts insert" on public.ava_attempts for insert to authenticated with check (user_id = (select auth.uid()));
create policy "ava own attendance readable" on public.ava_attendance for select to authenticated using (user_id = (select auth.uid()));
create policy "ava own certificates readable" on public.ava_certificates for select to authenticated using (user_id = (select auth.uid()));
create policy "ava own notifications readable" on public.ava_notifications for select to authenticated using (user_id = (select auth.uid()));
